// AU-S4 (docs/game-design/audio/02-audio-design.md §5.5, 05-production-plan AUC-U06): the game's sound bank.
// A bank id (the sound registry id: UI-SELECT, CMB-HIT-BLADE, VO-ARTHUR-ATTACK, MUS-MAP-MARMOREAL-L1, ...) maps to
// its variant soft paths (/Game/Audio/...). The table is generated by tools/audio/ue_bank.py from the finished audio
// (S08AudioBankData.inl, S08VoLinesData.inl) - the code never hardcodes an asset path.
//
// FS08SoundBag picks a variant without repeats (02 §3.2 anti-repeat, §4.4 "без повтора подряд"): every variant plays
// once before any plays again, and after a reshuffle the first pick is never the last one of the previous round.
// World-free and deterministic for a given random stream (tests, traces).
#pragma once

#include "CoreMinimal.h"
#include "Math/RandomStream.h"

/** One VO line of docs/game-design/audio/04-vo-script.md (S08VoLinesData.inl). */
struct UNMATCHED_API FS08VoLine {
  FString Id;       // ARTHUR-ATTACK-02
  FString Fighter;  // ARTHUR / MERLIN / MEDUSA
  FString Event;    // ATTACK / CARD-EXCALIBUR / ...
  FString En;       // the spoken text and the EN subtitle (empty for wordless efforts)
  FString Ru;       // the RU subtitle (empty for wordless efforts)
  FString Path;     // soft path of the SoundWave
};

namespace S08AudioBank {
/** The variants of a bank id (nullptr: not in the bank - the caller falls back, D10). */
UNMATCHED_API const TArray<FString>* Find(const FString& Id);
UNMATCHED_API int32 Num();
/** All VO lines in script order. */
UNMATCHED_API const TArray<FS08VoLine>& VoLines();
UNMATCHED_API const FS08VoLine* FindVoLine(const FString& LineId);
/** The VO line whose asset is SoftPath (subtitles of a picked variant). */
UNMATCHED_API const FS08VoLine* FindVoLineByPath(const FString& SoftPath);
/** Bank key of a fighter's character: "King Arthur" -> ARTHUR, "Merlin" -> MERLIN, "Medusa" -> MEDUSA, "Harpies 2" ->
 *  HARPY; empty for an unknown character (a future hero without VO: it stays silent, 02 §8.1). */
UNMATCHED_API FString CharacterKey(const FString& FighterNameOrLabel);
/** The hit / lunge type of a character (02 §4.5, the hit_type slot of §8.1): BLADE, CLAW, ARROW, MAGIC; BLUNT for an
 *  unknown character. */
UNMATCHED_API FString HitType(const FString& CharacterKey);
}  // namespace S08AudioBank

class UNMATCHED_API FS08SoundBag {
public:
  /** A variant of Variants for the bag Key (an empty string for an empty list). */
  FString Pick(const FString& Key, const TArray<FString>& Variants, FRandomStream& Rng);
  void Reset() { Bags.Reset(); }

private:
  struct FBag {
    TArray<int32> Order;
    int32 Next = 0;
    int32 Last = INDEX_NONE;
    int32 Size = 0;
  };
  TMap<FString, FBag> Bags;
};
