// DE-032 (W-25; 02 SD-51, R-12; CUE-DISPATCHER.md §3.2) + AU-S4 (docs/game-design/audio/02-audio-design.md §4-§5):
// the sound of the CUE sync points, world-free. It decides WHEN a sound plays, WHICH variant and with which gain; the
// assets come from the sound bank (S08AudioBank.h, generated by tools/audio/ue_bank.py - Kenney CC0, own synthesis,
// SYNTX generations; no Digital Edition sounds - EULA). A cue without an asset is a fallback show: the trace line is
// written, nothing plays, no error is logged (CUE-DISPATCHER.md §4 D10).
//
// The sync points (SD-51 pp. 1-5, the sound column of 07, 02 §4):
//   ui     - CUE-002 (own figure picked), CUE-003 (a choice accepted / a HUD press acted), CUE-004 (refused): in the
//            frame of the visual response of the release (UI-INP-011, SD-46);
//   hit    - CUE-011: in the contact frame of the lunge (the combat staging), not when the damage snapshot applies;
//            damage 0 plays the block (02 §6 p. 3); hits of one frame are one "multi" sound (02 §4.5);
//   step   - CUE-007: one sound per edge of a move, at the frame the figure starts that edge; a snapped move (reduced
//            motion, speed "none", past the seq cap) gives one sound at its landing;
//   turn   - CUE-015: the chime of the OWN turn only; the opponent's turn start is silent (WF1 AV-05);
//   result - CUE-016: the result sting starts with the result screen (RESULT screen line);
//   cue    - CUE-005/006/008/009/010/012/013/014/017/018 (AU-S4): in the frame of the visual event of the cue.
//
// The volumes (DE-025 storage, SD-55; AU-S4 buses 02 §5.1): "master" is the whole output (the adapter sets the audio
// device's transient primary volume); every class has its bus volume (Music / SFX / UI / VO / Ambience). They apply at
// once: a saved change writes `CUE audio … applied=change` and every later sound uses the new gain, no restart.
//
// Trace (CUE-DISPATCHER.md §5; gate AU1-AU11 in tools/s08/cue_contract/cue_contract.py check-trace):
//   CUE audio master=<0-100> master_mute=<0|1> ambience=<0-100> ambience_mute=<0|1> gain_master=<g> gain_ambience=<g>
//             music=<0-100> sfx=<0-100> ui=<0-100> vo=<0-100> subtitles=<0|1> t=<ms> applied=<start|change>
//   CUE sound id=<CUE-NNN> point=<ui|hit|step|turn|result|cue> subject=<id|-> seq=<N|-> t=<ms> event_t=<ms> dt=<ms>
//             class=<UI|SFX|Music|Ambience> sound=<name|missing|none> gain=<g> result=<played|fallback|silent|throttled>
//             [bank=<id>] [turn=own|opp] [edge=<k>/<n>|edge=snap due=<ms>] [reason=<opponent|muted|grouped>]
//   CUE sound drop point=step seq=<N> fighter=<id|*> t=<ms> count=<n> reason=<skip|replace>
#pragma once

#include "CoreMinimal.h"
#include "Math/RandomStream.h"
#include "S08AudioBank.h"
#include "S08UserSettings.h"

enum class ES08SoundPoint : uint8 { Ui, Hit, Step, Turn, Result, Cue };
enum class ES08SoundResult : uint8 { Played, Fallback, Silent, Throttled };

/** One sound row: the sfx block of a cue-table.json row, reduced to what the sound points decide on. */
struct UNMATCHED_API FS08SoundRow {
  FString CueId;
  FString SoundClass;  // UI / SFX / Music (cue-table sound_class)
  int32 Priority = 1;
  int32 RetriggerMs = 0;  // D8: concurrency.retrigger_ms
  FString SoundPath;      // cue-table sfx.sound: the first variant of the bank id (empty: none)
  FString BankId;         // cue-table sfx.bank: the default bank id of the cue (a request may override it)
};

namespace S08SoundRows {
/** Every CUE with a sound, as cue-table.json writes its sfx block (Unmatched.S08.CueSound.Table). */
UNMATCHED_API const TArray<FS08SoundRow>& All();
UNMATCHED_API const FS08SoundRow* Find(const FString& CueId);
UNMATCHED_API const TCHAR* PointName(ES08SoundPoint Point);
/** Short asset name of a soft path (/Game/Audio/SW_Hit.SW_Hit -> SW_Hit); empty for an empty path. */
UNMATCHED_API FString ShortName(const FString& SoftPath);
/** The ui CUE of a board release (07 CUE-002/003/004): refused (a toast / an illegal space) -> CUE-004; a command
 *  sent or a choice accepted -> CUE-003; an own figure picked -> CUE-002; another selection change -> CUE-003;
 *  nothing changed -> nullptr (no sound: the release had no visible response). */
UNMATCHED_API const TCHAR* BoardUiCue(bool bRefused, bool bCommand, bool bPickedOwn, bool bSelectionChanged);
}  // namespace S08SoundRows

/** One sound request at a sync point. EventMs is the frame time of the visual event the sound belongs to (the
 *  release response, the contact stage, the edge start, the banner, the result screen). */
struct UNMATCHED_API FS08SoundRequest {
  ES08SoundPoint Point = ES08SoundPoint::Ui;
  FString CueId;
  FString Subject;      // fighter / pressed id; empty = "-"
  int32 Seq = -1;       // -1 = "-"
  int64 EventMs = 0;
  bool bOwnTurn = true; // Turn only: false = the opponent's turn start (silent)
  int32 Edge = -1;      // Step only: edge index (0-based); -1 = a snapped move (one landing sound)
  int32 Edges = 0;      // Step only: edges of the move
  int64 DueMs = -1;     // Step only: the scheduled edge start (the schedule; the frame may land a bit later)
  FString BankId;       // AU-S4: the bank id for this event (hit type, death of a character); empty = the row's
};

/** What the adapter does with a decision: play SoundPath (if any) at ClassGain, as a UI sound when bUiSound. */
struct UNMATCHED_API FS08SoundDecision {
  ES08SoundResult Result = ES08SoundResult::Fallback;
  FString SoundPath;
  float ClassGain = 1.0f;  // the bus volume WITHOUT master (master is the device volume)
  float Gain = 1.0f;       // the effective gain (master x bus), traced
  bool bUiSound = false;
};

/** A scheduled step sound of a move (one per edge, or one landing sound of a snapped move). */
struct UNMATCHED_API FS08StepSound {
  FString FighterId;
  int32 Seq = -1;
  int64 DueMs = 0;
  int32 Edge = -1;
  int32 Edges = 0;
};

class UNMATCHED_API FS08CueSound {
public:
  FS08CueSound() : Rng(0x5EED) {}

  /** Short asset name of a soft path, or empty when the asset is not there (the adapter loads it). Unset: every bank
   *  path is taken as present. */
  TFunction<FString(const FString& SoftPath)> AssetResolver;

  /** The volumes in force from TMs (`CUE audio … applied=start|change`). A call with unchanged values writes nothing
   *  (false). */
  bool SetAudio(const FS08AudioSettings& Audio, int64 TMs, bool bStart, TArray<FString>& OutLines);
  const FS08AudioSettings& GetAudio() const { return Audio; }
  /** The gain of a sound class without master (its bus volume and mute) and with it. */
  float ClassGain(const FString& SoundClass) const;
  float EffectiveGain(const FString& SoundClass) const;

  /** One sound at a sync point, decided at NowMs (the frame it plays in). Unknown CueId: nothing, Silent. */
  FS08SoundDecision Play(const FS08SoundRequest& Request, int64 NowMs, TArray<FString>& OutLines);
  /** A hit of the same frame as an already played one: one "multi" sound covers it (02 §4.5) - traced
   *  `result=silent reason=grouped`, nothing plays. */
  void Grouped(const FS08SoundRequest& Request, int64 NowMs, TArray<FString>& OutLines);

  /** A variant of a bank id without repeats (music stings, ambience spots and VO use it too); empty: no such id. */
  FString PickVariant(const FString& BankId);

  /** CUE-007: the step sounds of one move - one per edge from StartMs every StepMs, or one at StartMs when snapped. */
  void ScheduleSteps(const FString& FighterId, int32 Seq, int64 StartMs, double StepMs, int32 Steps, bool bSnapped);
  /** The step sounds due at NowMs, in schedule order (each plays in this frame). */
  void TakeDueSteps(int64 NowMs, TArray<FS08StepSound>& OutDue);
  /** The pending step sounds are dropped - every one (a skip landed every move, reason=skip) or only FighterId's (its
   *  new move replaced the old one at its final pose, reason=replace): one `CUE sound drop` line per seq. */
  int32 DropSteps(int64 NowMs, const TCHAR* Reason, TArray<FString>& OutLines, const FString& FighterId = FString());
  int32 PendingSteps() const { return Steps.Num(); }

private:
  FS08AudioSettings Audio;
  bool bAudioSet = false;
  TMap<FString, int64> LastPlayed;  // D8 per CUE
  TArray<FS08StepSound> Steps;      // sorted by DueMs (stable)
  FS08SoundBag Bag;
  FRandomStream Rng;

  FString Line(const FS08SoundRequest& Request, const FS08SoundRow& Row, int64 NowMs, const FString& Sound, float Gain,
               ES08SoundResult Result, const FString& BankId, const TCHAR* Reason) const;
};
