// GENERATED by tools/s08/hud_contract/hud_tokens_codegen.py from docs/unreal/contracts/hud/hud-style-tokens.json.
// Do not edit: change the JSON and run the generator; hud_contract.py validate fails on a stale header (ВР-77).
// Colours are sRGB bytes: convert them ONLY with FLinearColor::FromSRGBColor (AD-OPEN-39, HUD-RULES П3).
// Alpha is a separate float; an alias takes the colour of its target, never its alpha.
#pragma once

#include "CoreMinimal.h"

namespace S08HudTokens {

/** sha256 of hud-style-tokens.json (CRLF -> LF) this header was generated from. */
inline constexpr const TCHAR* kTokensJsonSha256 = TEXT("176abf0e64e3d4d27cf8ab2da4ae13ed2d9726f772b105eba17fc97de0bae55f");

// ---- colours (60) ----
inline constexpr FColor Color_AccentWarm = FColor(0xFF, 0xB4, 0x5C, 0xFF);  // accent.warm #FFB45C
inline constexpr FColor Color_BoardChoice = FColor(0x4C, 0xD2, 0xDC, 0xFF);  // board.choice #4CD2DC
inline constexpr FColor Color_BoardKeyline = FColor(0x11, 0x13, 0x17, 0xFF);  // board.keyline #111317
inline constexpr FColor Color_BoardPath = FColor(0xFF, 0xC8, 0x57, 0xFF);  // board.path #FFC857
inline constexpr FColor Color_BoardPlateGrid = FColor(0xF2, 0xE9, 0xD8, 0xFF);  // board.plate.grid #F2E9D8
inline constexpr FColor Color_BoardReach = FColor(0xFF, 0xC8, 0x57, 0xFF);  // board.reach #FFC857
inline constexpr FColor Color_BoardTarget = FColor(0xF9, 0xEB, 0xDB, 0xFF);  // board.target #F9EBDB
inline constexpr FColor Color_CardCream = FColor(0xF9, 0xEB, 0xDB, 0xFF);  // card.cream #F9EBDB
inline constexpr FColor Color_CardGlyph = FColor(0xFA, 0xF8, 0xF2, 0xFF);  // card.glyph #FAF8F2
inline constexpr FColor Color_CardNavy = FColor(0x06, 0x16, 0x23, 0xFF);  // card.navy #061623
inline constexpr FColor Color_CardNavy2 = FColor(0x08, 0x27, 0x2E, 0xFF);  // card.navy.2 #08272E
inline constexpr FColor Color_CardTypeAttack = FColor(0xDC, 0x2F, 0x33, 0xFF);  // card.type.attack #DC2F33
inline constexpr FColor Color_CardTypeDefense = FColor(0x29, 0x76, 0xAE, 0xFF);  // card.type.defense #2976AE
inline constexpr FColor Color_CardTypeScheme = FColor(0xFD, 0xBE, 0x72, 0xFF);  // card.type.scheme #FDBE72
inline constexpr FColor Color_CardTypeVersatile = FColor(0x6B, 0x4E, 0x8F, 0xFF);  // card.type.versatile #6B4E8F
inline constexpr FColor Color_DamageText = FColor(0xFF, 0xE0, 0xAF, 0xFF);  // damage.text #FFE0AF
inline constexpr FColor Color_FxAsh = FColor(0xFF, 0xB4, 0x5C, 0xFF);  // fx.ash #FFB45C
inline constexpr FColor Color_FxAshP1 = FColor(0xDA, 0xC5, 0x76, 0xFF);  // fx.ash.p1 #DAC576
inline constexpr FColor Color_FxAshP2 = FColor(0x57, 0x86, 0xA8, 0xFF);  // fx.ash.p2 #5786A8
inline constexpr FColor Color_FxDust = FColor(0xB9, 0xB2, 0xA6, 0xFF);  // fx.dust #B9B2A6
inline constexpr FColor Color_FxDust2 = FColor(0xF9, 0xEB, 0xDB, 0xFF);  // fx.dust.2 #F9EBDB
inline constexpr FColor Color_FxFlash = FColor(0xFA, 0xF8, 0xF2, 0xFF);  // fx.flash #FAF8F2
inline constexpr FColor Color_FxGold = FColor(0xF2, 0xC1, 0x4E, 0xFF);  // fx.gold #F2C14E
inline constexpr FColor Color_FxHeal = FColor(0x8C, 0xE6, 0x9A, 0xFF);  // fx.heal #8CE69A
inline constexpr FColor Color_FxImpact = FColor(0xFF, 0xB4, 0x5C, 0xFF);  // fx.impact #FFB45C
inline constexpr FColor Color_FxRim = FColor(0xF9, 0xEB, 0xDB, 0xFF);  // fx.rim #F9EBDB
inline constexpr FColor Color_FxStone = FColor(0xF9, 0xEB, 0xDB, 0xFF);  // fx.stone #F9EBDB
inline constexpr FColor Color_FxStone2 = FColor(0xB9, 0xB2, 0xA6, 0xFF);  // fx.stone.2 #B9B2A6
inline constexpr FColor Color_HpBack = FColor(0x46, 0x1E, 0x1E, 0xFF);  // hp.back #461E1E
inline constexpr FColor Color_HpFill = FColor(0x50, 0xBE, 0x64, 0xFF);  // hp.fill #50BE64
inline constexpr FColor Color_IconTokenBody = FColor(0x06, 0x16, 0x23, 0xFF);  // icon.token.body #061623
inline constexpr FColor Color_IconTokenRim = FColor(0xF2, 0xEC, 0xDE, 0xFF);  // icon.token.rim #F2ECDE
inline constexpr FColor Color_LightKey = FColor(0xB8, 0xC8, 0xE0, 0xFF);  // light.key #B8C8E0
inline constexpr FColor Color_MarkKeyline = FColor(0x11, 0x13, 0x17, 0xFF);  // mark.keyline #111317
inline constexpr FColor Color_PanelBg = FColor(0x06, 0x16, 0x23, 0xFF);  // panel.bg #061623
inline constexpr FColor Color_PanelBgHover = FColor(0x1E, 0x2B, 0x35, 0xFF);  // panel.bg.hover #1E2B35
inline constexpr FColor Color_PanelBgInset = FColor(0x15, 0x23, 0x2E, 0xFF);  // panel.bg.inset #15232E
inline constexpr FColor Color_PanelBgPressed = FColor(0x04, 0x0E, 0x17, 0xFF);  // panel.bg.pressed #040E17
inline constexpr FColor Color_PanelDivider = FColor(0xF9, 0xEB, 0xDB, 0xFF);  // panel.divider #F9EBDB
inline constexpr FColor Color_PanelEdge = FColor(0xF9, 0xEB, 0xDB, 0xFF);  // panel.edge #F9EBDB
inline constexpr FColor Color_PanelVeil = FColor(0x06, 0x16, 0x23, 0xFF);  // panel.veil #061623
inline constexpr FColor Color_StateError = FColor(0xD9, 0x48, 0x3F, 0xFF);  // state.error #D9483F
inline constexpr FColor Color_StatePending = FColor(0x0D, 0x7A, 0x89, 0xFF);  // state.pending #0D7A89
inline constexpr FColor Color_StateWarning = FColor(0xE8, 0x81, 0x2C, 0xFF);  // state.warning #E8812C
inline constexpr FColor Color_TagBackground = FColor(0x06, 0x16, 0x23, 0xFF);  // tag.background #061623
inline constexpr FColor Color_TagText = FColor(0xF2, 0xED, 0xE4, 0xFF);  // tag.text #F2EDE4
inline constexpr FColor Color_TeamP1 = FColor(0xE8, 0xC0, 0x6A, 0xFF);  // team.p1 #E8C06A
inline constexpr FColor Color_TeamP1Screen = FColor(0xDA, 0xC5, 0x76, 0xFF);  // team.p1.screen #DAC576
inline constexpr FColor Color_TeamP2 = FColor(0x5A, 0x7F, 0x9F, 0xFF);  // team.p2 #5A7F9F
inline constexpr FColor Color_TeamP2Screen = FColor(0x57, 0x86, 0xA8, 0xFF);  // team.p2.screen #5786A8
inline constexpr FColor Color_TeamRim = FColor(0xFF, 0xFF, 0xFF, 0xFF);  // team.rim #FFFFFF
inline constexpr FColor Color_TextPrimary = FColor(0xF2, 0xED, 0xE4, 0xFF);  // text.primary #F2EDE4
inline constexpr FColor Color_TextSecondary = FColor(0xB9, 0xB2, 0xA6, 0xFF);  // text.secondary #B9B2A6
inline constexpr FColor Color_TurnFlashOrange = FColor(0xE8, 0x81, 0x2C, 0xFF);  // turn.flash.orange #E8812C
inline constexpr FColor Color_TurnFlashYellow = FColor(0xF2, 0xC1, 0x4E, 0xFF);  // turn.flash.yellow #F2C14E
inline constexpr FColor Color_ZoneBlue = FColor(0x3D, 0x7B, 0xDB, 0xFF);  // zone.blue #3D7BDB
inline constexpr FColor Color_ZoneGreen = FColor(0x3F, 0xA6, 0x5C, 0xFF);  // zone.green #3FA65C
inline constexpr FColor Color_ZonePurple = FColor(0x8A, 0x56, 0xC6, 0xFF);  // zone.purple #8A56C6
inline constexpr FColor Color_ZoneRed = FColor(0xD9, 0x48, 0x3F, 0xFF);  // zone.red #D9483F
inline constexpr FColor Color_ZoneYellow = FColor(0xE0, 0xB2, 0x3C, 0xFF);  // zone.yellow #E0B23C

// ---- alpha (7): colour tokens with an alpha field + the opacity group ----
inline constexpr float Alpha_PanelBg = 0.92f;  // panel.bg
inline constexpr float Alpha_PanelDivider = 0.16f;  // panel.divider
inline constexpr float Alpha_PanelEdge = 0.45f;  // panel.edge
inline constexpr float Alpha_PanelVeil = 0.6f;  // panel.veil
inline constexpr float Alpha_RingSmoulder = 0.35f;  // ring.smoulder
inline constexpr float Alpha_RingSmoulderS = 0.55f;  // ring.smoulder.s
inline constexpr float Alpha_StateDisabledOpacity = 0.4f;  // state.disabled.opacity

// ---- type scale (9), su at 1080p / 100 %; face = typeface of the default Slate composite font ----
inline constexpr int32 TypeSu_Banner = 36;  // type.banner
inline constexpr const TCHAR* TypeFace_Banner = TEXT("BoldCondensed");
inline constexpr bool TypeCaps_Banner = true;
inline constexpr int32 TypeSu_Body = 16;  // type.body
inline constexpr const TCHAR* TypeFace_Body = TEXT("Regular");
inline constexpr bool TypeCaps_Body = false;
inline constexpr int32 TypeSu_Button = 20;  // type.button
inline constexpr const TCHAR* TypeFace_Button = TEXT("BoldCondensed");
inline constexpr bool TypeCaps_Button = true;
inline constexpr int32 TypeSu_Caption = 14;  // type.caption
inline constexpr const TCHAR* TypeFace_Caption = TEXT("Regular");
inline constexpr bool TypeCaps_Caption = false;
inline constexpr int32 TypeSu_Damage = 24;  // type.damage
inline constexpr const TCHAR* TypeFace_Damage = TEXT("BoldCondensed");
inline constexpr bool TypeCaps_Damage = false;
inline constexpr int32 TypeSu_Display = 48;  // type.display
inline constexpr const TCHAR* TypeFace_Display = TEXT("BoldCondensed");
inline constexpr bool TypeCaps_Display = true;
inline constexpr int32 TypeSu_Heading = 24;  // type.heading
inline constexpr const TCHAR* TypeFace_Heading = TEXT("BoldCondensed");
inline constexpr bool TypeCaps_Heading = false;
inline constexpr int32 TypeSu_Tag = 14;  // type.tag
inline constexpr const TCHAR* TypeFace_Tag = TEXT("BoldCondensed");
inline constexpr bool TypeCaps_Tag = false;
inline constexpr int32 TypeSu_Title = 28;  // type.title
inline constexpr const TCHAR* TypeFace_Title = TEXT("BoldCondensed");
inline constexpr bool TypeCaps_Title = false;

// ---- Space (6) ----
inline constexpr float Space_PanelPadding = 12.0f;  // panel.padding
inline constexpr float Space_L = 24.0f;  // space.l
inline constexpr float Space_M = 16.0f;  // space.m
inline constexpr float Space_S = 12.0f;  // space.s
inline constexpr float Space_TagPaddingX = 4.0f;  // tag.padding.x
inline constexpr float Space_TagPaddingY = 2.0f;  // tag.padding.y

// ---- Radius (3) ----
inline constexpr float Radius_L = 8.0f;  // radius.l
inline constexpr float Radius_M = 6.0f;  // radius.m
inline constexpr float Radius_S = 4.0f;  // radius.s

// ---- MotionMs (14) ----
inline constexpr float MotionMs_Hover = 150.0f;  // hover.ms
inline constexpr float MotionMs_HpBarMaxMs = 400.0f;  // hp_bar.max_ms
inline constexpr float MotionMs_IconAppear = 180.0f;  // icon.appear.ms
inline constexpr float MotionMs_IconCyclePending = 1200.0f;  // icon.cycle.pending.ms
inline constexpr float MotionMs_IconCycleSent = 1500.0f;  // icon.cycle.sent.ms
inline constexpr float MotionMs_IconHpHit = 200.0f;  // icon.hp_hit.ms
inline constexpr float MotionMs_IconLeave = 120.0f;  // icon.leave.ms
inline constexpr float MotionMs_IconPress = 80.0f;  // icon.press.ms
inline constexpr float MotionMs_IconReconnect = 1200.0f;  // icon.reconnect.ms
inline constexpr float MotionMs_IconRibbonAppear = 220.0f;  // icon.ribbon.appear.ms
inline constexpr float MotionMs_IconSpinnerStep = 125.0f;  // icon.spinner.step.ms
inline constexpr float MotionMs_IconTap = 150.0f;  // icon.tap.ms
inline constexpr float MotionMs_ReducedMaxMs = 100.0f;  // reduced.max_ms
inline constexpr float MotionMs_Refuse = 350.0f;  // refuse.ms

// ---- IconPx (11) ----
inline constexpr int32 IconPx_DetailMin = 32;  // icon.detail_min
inline constexpr int32 IconPx_ExportMin = 16;  // icon.export_min
inline constexpr int32 IconPx_Keyline = 32;  // icon.keyline
inline constexpr int32 IconPx_L = 32;  // icon.l
inline constexpr int32 IconPx_M = 24;  // icon.m
inline constexpr int32 IconPx_Master = 1024;  // icon.master
inline constexpr int32 IconPx_Rim = 40;  // icon.rim
inline constexpr int32 IconPx_S = 16;  // icon.s
inline constexpr int32 IconPx_Stroke = 72;  // icon.stroke
inline constexpr int32 IconPx_TeamShape = 12;  // icon.team_shape
inline constexpr int32 IconPx_Xl = 48;  // icon.xl

// ---- name tables (theme fallback UUmHudTheme::BuildFromHeader, tests) ----
struct FColorToken { const TCHAR* Name; FColor Srgb; float Alpha; };
struct FScalarToken { const TCHAR* Name; float Value; };
struct FTypeToken { const TCHAR* Name; int32 Su; const TCHAR* Face; bool bCaps; };
struct FSkinToken { const TCHAR* Name; FColor Fill; float FillAlpha; FColor Edge; float EdgeAlpha; float EdgeSu; float RadiusSu; bool bHalfHeight; };

inline constexpr FColorToken kColors[] = {
    {TEXT("accent.warm"), FColor(0xFF, 0xB4, 0x5C, 0xFF), 1.0f},
    {TEXT("board.choice"), FColor(0x4C, 0xD2, 0xDC, 0xFF), 1.0f},
    {TEXT("board.keyline"), FColor(0x11, 0x13, 0x17, 0xFF), 1.0f},
    {TEXT("board.path"), FColor(0xFF, 0xC8, 0x57, 0xFF), 1.0f},
    {TEXT("board.plate.grid"), FColor(0xF2, 0xE9, 0xD8, 0xFF), 1.0f},
    {TEXT("board.reach"), FColor(0xFF, 0xC8, 0x57, 0xFF), 1.0f},
    {TEXT("board.target"), FColor(0xF9, 0xEB, 0xDB, 0xFF), 1.0f},
    {TEXT("card.cream"), FColor(0xF9, 0xEB, 0xDB, 0xFF), 1.0f},
    {TEXT("card.glyph"), FColor(0xFA, 0xF8, 0xF2, 0xFF), 1.0f},
    {TEXT("card.navy"), FColor(0x06, 0x16, 0x23, 0xFF), 1.0f},
    {TEXT("card.navy.2"), FColor(0x08, 0x27, 0x2E, 0xFF), 1.0f},
    {TEXT("card.type.attack"), FColor(0xDC, 0x2F, 0x33, 0xFF), 1.0f},
    {TEXT("card.type.defense"), FColor(0x29, 0x76, 0xAE, 0xFF), 1.0f},
    {TEXT("card.type.scheme"), FColor(0xFD, 0xBE, 0x72, 0xFF), 1.0f},
    {TEXT("card.type.versatile"), FColor(0x6B, 0x4E, 0x8F, 0xFF), 1.0f},
    {TEXT("damage.text"), FColor(0xFF, 0xE0, 0xAF, 0xFF), 1.0f},
    {TEXT("fx.ash"), FColor(0xFF, 0xB4, 0x5C, 0xFF), 1.0f},
    {TEXT("fx.ash.p1"), FColor(0xDA, 0xC5, 0x76, 0xFF), 1.0f},
    {TEXT("fx.ash.p2"), FColor(0x57, 0x86, 0xA8, 0xFF), 1.0f},
    {TEXT("fx.dust"), FColor(0xB9, 0xB2, 0xA6, 0xFF), 1.0f},
    {TEXT("fx.dust.2"), FColor(0xF9, 0xEB, 0xDB, 0xFF), 1.0f},
    {TEXT("fx.flash"), FColor(0xFA, 0xF8, 0xF2, 0xFF), 1.0f},
    {TEXT("fx.gold"), FColor(0xF2, 0xC1, 0x4E, 0xFF), 1.0f},
    {TEXT("fx.heal"), FColor(0x8C, 0xE6, 0x9A, 0xFF), 1.0f},
    {TEXT("fx.impact"), FColor(0xFF, 0xB4, 0x5C, 0xFF), 1.0f},
    {TEXT("fx.rim"), FColor(0xF9, 0xEB, 0xDB, 0xFF), 1.0f},
    {TEXT("fx.stone"), FColor(0xF9, 0xEB, 0xDB, 0xFF), 1.0f},
    {TEXT("fx.stone.2"), FColor(0xB9, 0xB2, 0xA6, 0xFF), 1.0f},
    {TEXT("hp.back"), FColor(0x46, 0x1E, 0x1E, 0xFF), 1.0f},
    {TEXT("hp.fill"), FColor(0x50, 0xBE, 0x64, 0xFF), 1.0f},
    {TEXT("icon.token.body"), FColor(0x06, 0x16, 0x23, 0xFF), 1.0f},
    {TEXT("icon.token.rim"), FColor(0xF2, 0xEC, 0xDE, 0xFF), 1.0f},
    {TEXT("light.key"), FColor(0xB8, 0xC8, 0xE0, 0xFF), 1.0f},
    {TEXT("mark.keyline"), FColor(0x11, 0x13, 0x17, 0xFF), 1.0f},
    {TEXT("panel.bg"), FColor(0x06, 0x16, 0x23, 0xFF), 0.92f},
    {TEXT("panel.bg.hover"), FColor(0x1E, 0x2B, 0x35, 0xFF), 1.0f},
    {TEXT("panel.bg.inset"), FColor(0x15, 0x23, 0x2E, 0xFF), 1.0f},
    {TEXT("panel.bg.pressed"), FColor(0x04, 0x0E, 0x17, 0xFF), 1.0f},
    {TEXT("panel.divider"), FColor(0xF9, 0xEB, 0xDB, 0xFF), 0.16f},
    {TEXT("panel.edge"), FColor(0xF9, 0xEB, 0xDB, 0xFF), 0.45f},
    {TEXT("panel.veil"), FColor(0x06, 0x16, 0x23, 0xFF), 0.6f},
    {TEXT("state.error"), FColor(0xD9, 0x48, 0x3F, 0xFF), 1.0f},
    {TEXT("state.pending"), FColor(0x0D, 0x7A, 0x89, 0xFF), 1.0f},
    {TEXT("state.warning"), FColor(0xE8, 0x81, 0x2C, 0xFF), 1.0f},
    {TEXT("tag.background"), FColor(0x06, 0x16, 0x23, 0xFF), 1.0f},
    {TEXT("tag.text"), FColor(0xF2, 0xED, 0xE4, 0xFF), 1.0f},
    {TEXT("team.p1"), FColor(0xE8, 0xC0, 0x6A, 0xFF), 1.0f},
    {TEXT("team.p1.screen"), FColor(0xDA, 0xC5, 0x76, 0xFF), 1.0f},
    {TEXT("team.p2"), FColor(0x5A, 0x7F, 0x9F, 0xFF), 1.0f},
    {TEXT("team.p2.screen"), FColor(0x57, 0x86, 0xA8, 0xFF), 1.0f},
    {TEXT("team.rim"), FColor(0xFF, 0xFF, 0xFF, 0xFF), 1.0f},
    {TEXT("text.primary"), FColor(0xF2, 0xED, 0xE4, 0xFF), 1.0f},
    {TEXT("text.secondary"), FColor(0xB9, 0xB2, 0xA6, 0xFF), 1.0f},
    {TEXT("turn.flash.orange"), FColor(0xE8, 0x81, 0x2C, 0xFF), 1.0f},
    {TEXT("turn.flash.yellow"), FColor(0xF2, 0xC1, 0x4E, 0xFF), 1.0f},
    {TEXT("zone.blue"), FColor(0x3D, 0x7B, 0xDB, 0xFF), 1.0f},
    {TEXT("zone.green"), FColor(0x3F, 0xA6, 0x5C, 0xFF), 1.0f},
    {TEXT("zone.purple"), FColor(0x8A, 0x56, 0xC6, 0xFF), 1.0f},
    {TEXT("zone.red"), FColor(0xD9, 0x48, 0x3F, 0xFF), 1.0f},
    {TEXT("zone.yellow"), FColor(0xE0, 0xB2, 0x3C, 0xFF), 1.0f},
};
inline constexpr FScalarToken kAlphas[] = {
    {TEXT("panel.bg"), 0.92f},
    {TEXT("panel.divider"), 0.16f},
    {TEXT("panel.edge"), 0.45f},
    {TEXT("panel.veil"), 0.6f},
    {TEXT("ring.smoulder"), 0.35f},
    {TEXT("ring.smoulder.s"), 0.55f},
    {TEXT("state.disabled.opacity"), 0.4f},
};
inline constexpr FTypeToken kTypes[] = {
    {TEXT("type.banner"), 36, TEXT("BoldCondensed"), true},
    {TEXT("type.body"), 16, TEXT("Regular"), false},
    {TEXT("type.button"), 20, TEXT("BoldCondensed"), true},
    {TEXT("type.caption"), 14, TEXT("Regular"), false},
    {TEXT("type.damage"), 24, TEXT("BoldCondensed"), false},
    {TEXT("type.display"), 48, TEXT("BoldCondensed"), true},
    {TEXT("type.heading"), 24, TEXT("BoldCondensed"), false},
    {TEXT("type.tag"), 14, TEXT("BoldCondensed"), false},
    {TEXT("type.title"), 28, TEXT("BoldCondensed"), false},
};
inline constexpr FScalarToken kSpace[] = {
    {TEXT("panel.padding"), 12.0f},
    {TEXT("space.l"), 24.0f},
    {TEXT("space.m"), 16.0f},
    {TEXT("space.s"), 12.0f},
    {TEXT("tag.padding.x"), 4.0f},
    {TEXT("tag.padding.y"), 2.0f},
};
inline constexpr FScalarToken kRadius[] = {
    {TEXT("radius.l"), 8.0f},
    {TEXT("radius.m"), 6.0f},
    {TEXT("radius.s"), 4.0f},
};
inline constexpr FScalarToken kMotionMs[] = {
    {TEXT("hover.ms"), 150.0f},
    {TEXT("hp_bar.max_ms"), 400.0f},
    {TEXT("icon.appear.ms"), 180.0f},
    {TEXT("icon.cycle.pending.ms"), 1200.0f},
    {TEXT("icon.cycle.sent.ms"), 1500.0f},
    {TEXT("icon.hp_hit.ms"), 200.0f},
    {TEXT("icon.leave.ms"), 120.0f},
    {TEXT("icon.press.ms"), 80.0f},
    {TEXT("icon.reconnect.ms"), 1200.0f},
    {TEXT("icon.ribbon.appear.ms"), 220.0f},
    {TEXT("icon.spinner.step.ms"), 125.0f},
    {TEXT("icon.tap.ms"), 150.0f},
    {TEXT("reduced.max_ms"), 100.0f},
    {TEXT("refuse.ms"), 350.0f},
};
inline constexpr FScalarToken kIconPx[] = {
    {TEXT("icon.detail_min"), 32.0f},
    {TEXT("icon.export_min"), 16.0f},
    {TEXT("icon.keyline"), 32.0f},
    {TEXT("icon.l"), 32.0f},
    {TEXT("icon.m"), 24.0f},
    {TEXT("icon.master"), 1024.0f},
    {TEXT("icon.rim"), 40.0f},
    {TEXT("icon.s"), 16.0f},
    {TEXT("icon.stroke"), 72.0f},
    {TEXT("icon.team_shape"), 12.0f},
    {TEXT("icon.xl"), 48.0f},
};
/** Rounded-box fallback skins (ВР-HB06): HB-10 replaces them with 9-slice PNG under the same names. */
inline constexpr FSkinToken kSkins[] = {
    {TEXT("btn.disabled"), FColor(0x06, 0x16, 0x23, 0xFF), 1.0f, FColor(0xF9, 0xEB, 0xDB, 0xFF), 0.16f, 1.0f, 4.0f, false},
    {TEXT("btn.focus"), FColor(0xFA, 0xF8, 0xF2, 0xFF), 0.0f, FColor(0xFA, 0xF8, 0xF2, 0xFF), 1.0f, 2.0f, 8.0f, false},
    {TEXT("btn.hover"), FColor(0x1E, 0x2B, 0x35, 0xFF), 1.0f, FColor(0xF9, 0xEB, 0xDB, 0xFF), 1.0f, 1.0f, 4.0f, false},
    {TEXT("btn.normal"), FColor(0x06, 0x16, 0x23, 0xFF), 1.0f, FColor(0xF9, 0xEB, 0xDB, 0xFF), 0.45f, 1.0f, 4.0f, false},
    {TEXT("btn.pressed"), FColor(0x04, 0x0E, 0x17, 0xFF), 1.0f, FColor(0xF9, 0xEB, 0xDB, 0xFF), 0.45f, 1.0f, 4.0f, false},
    {TEXT("btn.primary.disabled"), FColor(0xB9, 0xB2, 0xA6, 0xFF), 0.4f, FColor(0x06, 0x16, 0x23, 0xFF), 1.0f, 1.0f, 4.0f, false},
    {TEXT("btn.primary.focus"), FColor(0xFA, 0xF8, 0xF2, 0xFF), 0.0f, FColor(0xFA, 0xF8, 0xF2, 0xFF), 1.0f, 2.0f, 8.0f, false},
    {TEXT("btn.primary.hover"), FColor(0xF3, 0xC5, 0x5B, 0xFF), 1.0f, FColor(0x06, 0x16, 0x23, 0xFF), 1.0f, 1.0f, 4.0f, false},
    {TEXT("btn.primary.normal"), FColor(0xF2, 0xC1, 0x4E, 0xFF), 1.0f, FColor(0x06, 0x16, 0x23, 0xFF), 1.0f, 1.0f, 4.0f, false},
    {TEXT("btn.primary.pressed"), FColor(0xD5, 0xAA, 0x45, 0xFF), 1.0f, FColor(0x06, 0x16, 0x23, 0xFF), 1.0f, 1.0f, 4.0f, false},
    {TEXT("btn.selected"), FColor(0x0D, 0x7A, 0x89, 0xFF), 1.0f, FColor(0xFA, 0xF8, 0xF2, 0xFF), 1.0f, 1.0f, 4.0f, false},
    {TEXT("capsule"), FColor(0x06, 0x16, 0x23, 0xFF), 1.0f, FColor(0x00, 0x00, 0x00, 0xFF), 0.0f, 0.0f, 0.0f, true},
    {TEXT("check.off"), FColor(0x15, 0x23, 0x2E, 0xFF), 1.0f, FColor(0xF9, 0xEB, 0xDB, 0xFF), 0.45f, 1.0f, 4.0f, false},
    {TEXT("check.on"), FColor(0x0D, 0x7A, 0x89, 0xFF), 1.0f, FColor(0xFA, 0xF8, 0xF2, 0xFF), 1.0f, 1.0f, 4.0f, false},
    {TEXT("chip"), FColor(0x15, 0x23, 0x2E, 0xFF), 1.0f, FColor(0xF9, 0xEB, 0xDB, 0xFF), 0.45f, 1.0f, 4.0f, false},
    {TEXT("input.error"), FColor(0x15, 0x23, 0x2E, 0xFF), 1.0f, FColor(0xE8, 0x81, 0x2C, 0xFF), 1.0f, 2.0f, 4.0f, false},
    {TEXT("input.focus"), FColor(0x15, 0x23, 0x2E, 0xFF), 1.0f, FColor(0xF9, 0xEB, 0xDB, 0xFF), 1.0f, 1.0f, 4.0f, false},
    {TEXT("input.normal"), FColor(0x15, 0x23, 0x2E, 0xFF), 1.0f, FColor(0xF9, 0xEB, 0xDB, 0xFF), 0.45f, 1.0f, 4.0f, false},
    {TEXT("key.chip"), FColor(0x15, 0x23, 0x2E, 0xFF), 1.0f, FColor(0xF9, 0xEB, 0xDB, 0xFF), 0.45f, 1.0f, 4.0f, false},
    {TEXT("modal"), FColor(0x06, 0x16, 0x23, 0xFF), 1.0f, FColor(0xF9, 0xEB, 0xDB, 0xFF), 0.45f, 1.0f, 8.0f, false},
    {TEXT("panel"), FColor(0x06, 0x16, 0x23, 0xFF), 0.92f, FColor(0xF9, 0xEB, 0xDB, 0xFF), 0.45f, 1.0f, 6.0f, false},
    {TEXT("panel.inset"), FColor(0x15, 0x23, 0x2E, 0xFF), 1.0f, FColor(0x00, 0x00, 0x00, 0xFF), 0.0f, 0.0f, 4.0f, false},
    {TEXT("progress.fill"), FColor(0xF9, 0xEB, 0xDB, 0xFF), 1.0f, FColor(0x00, 0x00, 0x00, 0xFF), 0.0f, 0.0f, 0.0f, true},
    {TEXT("progress.track"), FColor(0x15, 0x23, 0x2E, 0xFF), 1.0f, FColor(0xF9, 0xEB, 0xDB, 0xFF), 0.45f, 1.0f, 0.0f, true},
    {TEXT("slider.thumb"), FColor(0xF9, 0xEB, 0xDB, 0xFF), 1.0f, FColor(0x11, 0x13, 0x17, 0xFF), 1.0f, 1.0f, 0.0f, true},
    {TEXT("slider.track"), FColor(0x15, 0x23, 0x2E, 0xFF), 1.0f, FColor(0xF9, 0xEB, 0xDB, 0xFF), 0.45f, 1.0f, 0.0f, true},
    {TEXT("tag"), FColor(0x06, 0x16, 0x23, 0xFF), 1.0f, FColor(0x00, 0x00, 0x00, 0xFF), 0.0f, 0.0f, 0.0f, true},
    {TEXT("toast"), FColor(0x06, 0x16, 0x23, 0xFF), 0.92f, FColor(0xF9, 0xEB, 0xDB, 0xFF), 0.45f, 1.0f, 0.0f, true},
    {TEXT("toast.warning"), FColor(0x06, 0x16, 0x23, 0xFF), 0.92f, FColor(0xE8, 0x81, 0x2C, 0xFF), 1.0f, 2.0f, 0.0f, true},
};
inline constexpr int32 kNumSkins = 29;

}  // namespace S08HudTokens
