"""Import manifest and generated C++ tables of the game's sound bank (card AUC-U06, 02 §5.5).

    python tools/audio/ue_bank.py --final C:/tmp/audio-src/final --manifest C:/tmp/audio-src/ue-import.json
           --cpp-out <repo>/unreal/Unmatched/Source/Unmatched/S08

Scans the finished audio (music / stings / sfx / amb / vo under --final) and writes
- the import manifest for tools/audio/ue_import_audio.py: source WAV -> /Game/Audio/<Folder>/SW_<ID> (+ loop flag);
- S08AudioBankData.inl: bank id -> variant soft paths (UI-SELECT -> 3 variants, VO-ARTHUR-ATTACK -> 4 lines, ...);
- S08VoLinesData.inl: one row per VO line (id, fighter, event, EN text, RU subtitle, soft path), texts from
  docs/game-design/audio/04-vo-script.md, non-ASCII as \\u escapes (no source-encoding dependency).
Asset names: the registry id with '-' -> '_' (SW_UI_SELECT_01, SW_MUS_MAP_MARMOREAL_L1, SW_VO_ARTHUR_ATTACK_02).
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from collections import OrderedDict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from vo_batch import lines as script_lines  # noqa: E402

FOLDER = {"UI": "UI", "CRD": "Cards", "BRD": "Board", "CMB": "Combat", "DTH": "Death", "FX": "FX", "STG": "Stings",
          "AMB": "Amb", "MUS": "Music"}
HEADER = "// Generated by tools/audio/ue_bank.py - do not edit (rerun the script after the audio changes).\n"


def asset(folder: str, name: str) -> str:
    return f"/Game/Audio/{folder}/{name}.{name}"


def cpp_str(s: str) -> str:
    out = []
    for ch in s:
        if ch == '"' or ch == "\\":
            out.append("\\" + ch)
        elif ord(ch) < 128:
            out.append(ch)
        else:
            out.append(f"\\u{ord(ch):04X}")
    return "".join(out)


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--final", required=True)
    ap.add_argument("--manifest", required=True)
    ap.add_argument("--cpp-out", required=True)
    args = ap.parse_args(argv)
    final = Path(args.final)
    items: list[dict] = []
    bank: "OrderedDict[str, list[str]]" = OrderedDict()

    def add(bank_id: str, src: Path, folder: str, name: str, loop: bool = False) -> None:
        items.append({"src": str(src).replace("\\", "/"), "dest": f"/Game/Audio/{folder}", "name": name,
                      "loop": loop})
        bank.setdefault(bank_id, []).append(asset(folder, name))

    # music: two layers per theme
    for f in sorted((final / "music").glob("*-L[12]_16.wav")):
        m = re.match(r"(.+)-(L[12])_16\.wav$", f.name)
        uid = f"{m.group(1)}-{m.group(2)}"
        add(uid, f, "Music", "SW_" + uid.replace("-", "_"), loop=True)
    # stings (Suno cuts) and the logo
    for f in sorted((final / "stings").glob("*_16.wav")):
        uid = f.name[: -len("_16.wav")]
        add(uid, f, "Stings" if uid.startswith("STG") else "UI", "SW_" + uid.replace("-", "_"))
    # sfx variants <ID>_NN.wav
    for f in sorted((final / "sfx").glob("*_[0-9][0-9].wav")):
        uid = f.stem[:-3]
        add(uid, f, FOLDER[uid.split("-")[0]], "SW_" + f.stem.replace("-", "_"))
    # ambience: beds (loops) and spots
    for f in sorted((final / "amb").glob("AMB-*.wav")):
        m = re.match(r"(.+?)(?:_(\d\d))?\.wav$", f.name)
        uid = m.group(1)
        add(uid, f, "Amb", "SW_" + f.stem.replace("-", "_"), loop=m.group(2) is None)
    # VO lines: bank id VO-<FIGHTER>-<EVENT>, variants in script order
    vo_rows = []
    for ln in script_lines():
        src = final / "vo" / f"{ln['id']}.wav"
        if not src.exists():
            continue
        fighter = ln["fighter"]
        event = re.sub(r"-\d\d$", "", ln["id"][len(fighter) + 1:])
        name = "SW_VO_" + ln["id"].replace("-", "_")
        folder = f"VO/{fighter.title()}"
        add(f"VO-{fighter}-{event}", src, folder, name)
        vo_rows.append((ln["id"], fighter, event, ln["en"], ln["ru"], asset(folder, name)))
    # harpy cries: VO-HARPY-<EVENT>-H<k>
    for f in sorted((final / "vo").glob("HARPY-*-H[123].wav")):
        m = re.match(r"HARPY-(.+)-(\d\d)-H(\d)\.wav$", f.name)
        event, k = m.group(1), m.group(3)
        add(f"VO-HARPY-{event}-H{k}", f, "VO/Harpy", "SW_VO_" + f.stem.replace("-", "_"))
    # FX voice layers
    for f in sorted((final / "vo").glob("FX-*-VOICE.wav")):
        add(f.stem, f, "FX", "SW_" + f.stem.replace("-", "_"))

    Path(args.manifest).write_text(json.dumps(items, indent=1), encoding="utf-8")
    out = Path(args.cpp_out)
    bank_lines = [HEADER, "// S08_AUDIO_BANK(Id, \"path|path|...\")\n"]
    for k, paths in bank.items():
        bank_lines.append(f'S08_AUDIO_BANK(TEXT("{k}"), TEXT("{"|".join(paths)}"))\n')
    (out / "S08AudioBankData.inl").write_text("".join(bank_lines), encoding="utf-8")
    vo_lines = [HEADER, "// S08_VO_LINE(Id, Fighter, Event, En, Ru, SoftPath)\n"]
    for lid, fighter, event, en, ru, path in vo_rows:
        vo_lines.append(f'S08_VO_LINE(TEXT("{lid}"), TEXT("{fighter}"), TEXT("{event}"), TEXT("{cpp_str(en)}"), '
                        f'TEXT("{cpp_str(ru)}"), TEXT("{path}"))\n')
    (out / "S08VoLinesData.inl").write_text("".join(vo_lines), encoding="utf-8")
    print(json.dumps({"assets": len(items), "bank_ids": len(bank), "vo_lines": len(vo_rows)}))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
