query GetCards($page: Int!, $limit: Int!) {
  cardList(page: $page, limit: $limit) {
    items {
      id
      name
      nameEn
      nameRu
      cardType
      subType
      attackValue
      defenseValue
      boostValue
      bannerName
      count
      heroId
      imageUrl
      imageUrlRu
    }
    total
  }
}

query GetCard($id: String!) {
  card(id: $id) {
    id
    title
    type
    value
    boost
    quantity
    characterName
    imageUrl
    imageUrlRu
    effects {
      id
      timing
      text
    }
  }
}
